import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const auto = readFileSync(new URL("./kayAutoRescueService.ts", import.meta.url), "utf8");
const rescue = readFileSync(new URL("./kayRescueService.ts", import.meta.url), "utf8");
const routes = readFileSync(new URL("./routes.ts", import.meta.url), "utf8");
const db = readFileSync(new URL("./db.ts", import.meta.url), "utf8");
const schema = readFileSync(new URL("../shared/schema.ts", import.meta.url), "utf8");

test("E.2 static safety contract covers the non-runtime portions of the 62-item matrix", () => {
  assert.match(auto,/mode !== "controlled_automation"/,"1-3 controlled mode is mandatory");
  assert.match(auto,/auto_rescue_kill_switch/,"4 kill switch is mandatory");
  assert.match(auto,/auto_rescue_no_answer_1_enabled/,"5 NA1 rule gate exists");
  assert.match(auto,/auto_rescue_canary_employee_ids/,"6 explicit canary gate exists");
  assert.match(rescue,/THRESHOLD_NOT_MET/,"7 threshold boundary fails closed");
  assert.match(auto,/lead\.status === "no_answer_1"/,"8 NA1 is explicit");
  assert.match(auto,/no_answer_2_threshold_hours/,"9 NA2 is explicit");
  assert.doesNotMatch(auto,/status IN \([^)]*no_answer_3/,"10-11 NA3 is not queried");
  assert.doesNotMatch(auto,/status IN \([^)]*no_answer_4/,"10-11 NA4 is not queried");
  assert.match(rescue,/throw reject\("PROTECTED"\)/,"12 protection is revalidated");
  assert.match(rescue,/crm_tasks[\s\S]*throw reject\("BLOCKER_ADDED"\)/,"13-14 task and follow-up blockers are revalidated");
  assert.match(rescue,/rule_status !== lead\.status/,"15 status race is fenced");
  assert.match(rescue,/lead\.assigned_to !== command\.expectedOwnerId/,"16 owner race is fenced");
  assert.match(rescue,/FOR UPDATE OF l/,"17 protection and lead state share the locked transaction");
  assert.match(rescue,/target\.rows\[0\]\.is_active !== true/,"18 inactive target is rejected");
  assert.match(rescue,/availability !== "AVAILABLE"/,"19 leave, busy, and do-not-assign are rejected");
  assert.match(rescue,/targetId === lead\.assigned_to/,"20 same employee is rejected");
  assert.match(auto,/NO_ELIGIBLE_EMPLOYEE/,"21 no target creates manager review");
  assert.match(rescue,/PING_PONG_PREVENTED/,"22 ping-pong is prevented");
  assert.match(rescue,/LIMIT_REACHED/,"23 maximum attempts are enforced");
  assert.match(rescue,/pg_advisory_xact_lock/,"24-25 daily limits are concurrency serialized");
  assert.match(auto,/e2:warning:/,"26 warning mission is idempotent");
  assert.match(auto,/e2:warning-notification:/,"27 warning notification is deduplicated");
  assert.match(auto,/grace_count=grace_count\+1/,"28 grace is durable");
  assert.match(auto,/grace_count<\$3/,"29 grace maximum is atomic");
  assert.match(auto,/grace_until<=NOW\(\)/,"30 expired grace returns to ready");
  assert.match(auto,/CANNOT_HANDLE[\s\S]*MANAGER_REVIEW/,"31 cannot-handle only requests review");
  assert.match(rescue,/UPDATE crm_leads SET assigned_to/,"32 the shared transaction performs the sole ownership write");
  assert.match(rescue,/kay_rescue_automatic/,"33 automatic history is explicit");
  assert.match(rescue,/stale_reason":"LEAD_REASSIGNED"/,"34-35 mission and commitment stale reason is exact");
  assert.match(rescue,/SELECT id,employee_id FROM kay_promises/,"36 promises are preserved");
  assert.match(rescue,/INSERT INTO kay_promise_handoffs/,"37 promise handoff is created");
  assert.match(rescue,/RESCUE_LEAD_ASSIGNED/,"38 new-owner mission is created");
  assert.match(rescue,/new-brief/,"39 new-owner briefing is created");
  assert.match(rescue,/old-brief/,"40 old-owner notice is created");
  assert.match(auto,/FOR UPDATE SKIP LOCKED/,"41 concurrent workers claim once");
  assert.match(rescue,/prior\.rows\[0\]/,"42 committed retry is idempotent");
  assert.match(rescue,/ROLLBACK/,"43 transaction failures roll back");
  assert.match(auto,/reconcileUncertain/,"44 uncertain results reconcile before retry");
  assert.match(routes,/rescue\/:executionId\/undo/,"45 undo remains admin-accessible");
  assert.match(rescue,/MANUAL_REVIEW_REQUIRED/,"46 unsafe undo fails closed");
  assert.match(auto,/halted:n>=3/,"47 three infrastructure failures halt the circuit");
  assert.match(auto,/businessRejections\.has/,"48 business rejections do not count as infrastructure failures");
  assert.match(auto,/runKayAutoRescueWorker\(\)\.catch\(\(\)=>\{\}\)/,"49 scheduler failure is isolated");
  assert.doesNotMatch(auto,/UPDATE crm_leads SET\s+status/i,"50 worker never changes CRM status");
  assert.doesNotMatch(auto,/whatsapp|twilio|sendEmail|sendSMS/i,"51-53 worker has no customer communication dependency");
  assert.match(routes,/settings\/rescue", requireKayAdmin/,"54 rescue settings are admin-only");
  assert.match(routes,/auto-rescue\/run", requireKayAdmin/,"55 employees cannot operate worker or kill switch");
  assert.doesNotMatch(rescue,/full_approved_automation/,"56 full automation is absent");
  assert.match(auto,/Read-only aggregate simulation/,"57 dry-run is explicitly read-only");
  assert.match(db,/auto_rescue_no_answer_1_enabled' THEN NULL ELSE false/,"production NA1 default remains false");
  assert.match(db,/auto_rescue_no_answer_2_enabled' THEN NULL ELSE false/,"production NA2 default remains false");
  assert.match(db,/auto_rescue_kill_switch' THEN NULL ELSE true/,"production kill switch default remains on");
  assert.match(schema,/kay_auto_rescue_queue_identity_unique_idx/,"queue identity has a database uniqueness constraint");
  assert.match(schema,/fencingToken/,"queue schema persists fencing token");
  assert.match(routes,/aggregateOnly: true/,"dry-run returns aggregates only");
});

test("E.2 warning mission revalidates current owner and shared scope under lock", () => {
  const warning = auto.slice(auto.indexOf("async function ensureWarningArtifacts"), auto.indexOf("async function evaluateIntoQueue"));
  assert.match(warning, /JOIN crm_leads l ON l\.id=q\.lead_id[\s\S]*FOR UPDATE OF q,l/);
  assert.match(warning, /getKayScopeForLead\(leadId, client\)/);
  assert.match(warning, /scope\.outcome !== "IN_KAY_SCOPE"[\s\S]*item\.assigned_to[\s\S]*ownerId/);
  assert.ok(warning.indexOf("getKayScopeForLead(leadId, client)") < warning.indexOf("INSERT INTO kay_missions"));
});