import { useMutation, useQuery } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/lib/auth";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, CheckCircle2, Clock, ExternalLink, Plus, Volume2, ArrowRight, ShieldAlert } from "lucide-react";

type Mission = { id:number; leadId:number|null; missionType:string; priority:string; priorityScore:number; status:string; objective:string; suggestedAction:string; reasonDetails?: { explanation?:string; factors?: { label:string; points:number }[] }; dueAt?:string|null };
type Data = { missions: Mission[]; next60Minutes: Mission[]; settings:{max_next_60_minutes_items:number} };
type Briefing = { id:number;text:string;acknowledgedAt?:string|null;deepLink?:string|null;severity:string };
type Commitment = { id:number;action:string;status:string;dueAt:string; missionId?:number };
type PromiseItem = { id:number;promiseText:string;status:string;importance:string;dueAt:string };
type Handoff = { id:number; promise_text:string; promiseText?:string; due_at:string; dueAt?:string; original_owner_id:number; accepted_at?:string|null; importance?:string };
const colors: Record<string,string> = { CRITICAL:"bg-red-100 text-red-700", HIGH:"bg-orange-100 text-orange-700", NORMAL:"bg-amber-100 text-amber-700", LOW:"bg-slate-100 text-slate-700" };
const localDate = (value?:string|null) => value ? new Date(value).toLocaleString([], { dateStyle:"medium", timeStyle:"short" }) : "No due date";
const dueBucket = (p: PromiseItem) => p.status === "COMPLETED" ? "Completed Today" : new Date(p.dueAt) < new Date() ? "Overdue" : new Date(p.dueAt).getTime() < Date.now()+86400000*2 ? "Due Soon" : "Upcoming";

export default function KayMySalesPage() {
  const { user, isLoading: authLoading } = useAuth(); const [, navigate] = useLocation();
  const allowed = !!user && (!!user.isAdmin || user.role === "sub_agent");
  useEffect(() => { if (!authLoading && !allowed) navigate("/"); }, [allowed, authLoading, navigate]);
  const query = useQuery<Data>({ queryKey:["/api/kay/missions"], queryFn: async () => (await apiRequest("GET","/api/kay/missions")).json(), enabled: allowed });
  const completed = useQuery<Data>({ queryKey:["/api/kay/missions","completed"], queryFn: async () => (await apiRequest("GET","/api/kay/missions?completed=true")).json(), enabled: allowed });
  const availability = useQuery<{availability:string}>({ queryKey:["/api/kay/availability"], queryFn: async () => (await apiRequest("GET","/api/kay/availability")).json(), enabled: allowed });
  const briefings = useQuery<{briefings:Briefing[]}>({ queryKey:["/api/kay/briefings"], queryFn:async()=> (await apiRequest("GET","/api/kay/briefings")).json(), enabled:allowed });
  const commitments = useQuery<{commitments:Commitment[]}>({ queryKey:["/api/kay/commitments"], queryFn:async()=> (await apiRequest("GET","/api/kay/commitments")).json(), enabled:allowed });
  const promises = useQuery<{promises:PromiseItem[]}>({ queryKey:["/api/kay/promises"], queryFn:async()=> (await apiRequest("GET","/api/kay/promises")).json(), enabled:allowed });
  const handoffs = useQuery<{handoffs:Handoff[]}>({ queryKey:["/api/kay/promise-handoffs"], queryFn:async()=> (await apiRequest("GET","/api/kay/promise-handoffs")).json(), enabled:allowed });
  const voice = useQuery<any>({ queryKey:["/api/kay/settings/phase-d"], queryFn:async()=> (await apiRequest("GET","/api/kay/settings/phase-d")).json(), enabled:allowed });
  useEffect(() => {
    const refresh = () => {
      query.refetch();
      commitments.refetch();
      promises.refetch();
      briefings.refetch();
      handoffs.refetch();
    };
    window.addEventListener("focus", refresh);
    return () => window.removeEventListener("focus", refresh);
  }, [query.refetch, commitments.refetch, promises.refetch, briefings.refetch, handoffs.refetch]);
  const updateAvailability = useMutation({ mutationFn: async (value:string) => (await apiRequest("PUT","/api/kay/availability",{availability:value})).json(), onSuccess: () => queryClient.invalidateQueries({queryKey:["/api/kay/availability"]}) });
  const action = useMutation({ mutationFn: async ({id, action, payload}:{id:number; action:string; payload?:any}) => (await apiRequest("POST",`/api/kay/missions/${id}/${action}`, payload ?? {})).json(), onSuccess: () => { queryClient.invalidateQueries({queryKey:["/api/kay/missions"]}); queryClient.invalidateQueries({queryKey:["/api/kay/commitments"]}); } });
  const briefingAction = useMutation({mutationFn:async(id:number)=>(await apiRequest("POST",`/api/kay/briefings/${id}/acknowledge`,{})).json(),onSuccess:()=>queryClient.invalidateQueries({queryKey:["/api/kay/briefings"]})});
  const commitmentAction = useMutation({mutationFn:async({id,action,dueAt}:{id:number;action:"accept"|"complete"|"extend";dueAt?:string})=>(await apiRequest("POST",`/api/kay/commitments/${id}/${action}`,dueAt?{dueAt}:{})).json(),onSuccess:()=>queryClient.invalidateQueries({queryKey:["/api/kay/commitments"]})});
  const promiseAction = useMutation({mutationFn:async({id,action}:{id:number;action:"complete"|"cancel"})=>(await apiRequest("POST",`/api/kay/promises/${id}/${action}`,{})).json(),onSuccess:()=>queryClient.invalidateQueries({queryKey:["/api/kay/promises"]})});
  const handoffAction = useMutation({mutationFn:async(id:number)=>(await apiRequest("POST",`/api/kay/promise-handoffs/${id}/accept`,{})).json(),onSuccess:()=>queryClient.invalidateQueries({queryKey:["/api/kay/promise-handoffs"]})});
  const [promiseOpen,setPromiseOpen] = useState(false);
  if (authLoading || !allowed) return null;
  const missions = query.data?.missions ?? [];
  const today = new Date().toDateString();
  const sections:[string,Mission[]][] = [["Priority Queue",missions],["Rescue Risk",missions.filter(m=>m.missionType==="RESCUE_RISK")],["Follow-ups",missions.filter(m=>m.missionType==="FOLLOW_UP_DUE")],["Unprotected Opportunities",missions.filter(m=>m.missionType==="UNPROTECTED_LEAD")],["Completed Today",(completed.data?.missions ?? []).filter((m:any)=>m.status==="COMPLETED" && m.completedAt && new Date(m.completedAt).toDateString()===today)]];
  const speak = (text:string) => { if ("speechSynthesis" in window) { window.speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); const language=voice.data?.profile?.language??voice.data?.default_language; u.lang=language==="ar"?"ar-SA":"en-US"; u.rate=Number(voice.data?.speech_rate??1); u.pitch=Number(voice.data?.speech_pitch??1); const preferred=voice.data?.profile?.preferred_voice_name??voice.data?.preferred_voice_name; if(preferred){const selected=window.speechSynthesis.getVoices().find(v=>v.name===preferred);if(selected)u.voice=selected;} window.speechSynthesis.speak(u); } };
  return <div className="min-h-[100dvh] max-w-5xl mx-auto p-4 sm:p-6 space-y-5">
    <header className="rounded-2xl bg-gradient-to-r from-[#005476] to-[#3bcac4] text-white p-5"><div className="flex gap-3"><Bot/><div><h1 className="text-xl font-bold">Kay — My Sales</h1><p className="text-sm text-white/85">Kay Missions protect the deal with clear next steps. CRM stays unchanged.</p></div></div></header>
    <Card><CardHeader><CardTitle className="text-[#005476]">Internal Kay briefings</CardTitle></CardHeader><CardContent className="space-y-2">{(briefings.data?.briefings??[]).filter(b=>!b.acknowledgedAt).length===0?<p className="text-sm text-muted-foreground">No new internal briefings.</p>:(briefings.data?.briefings??[]).filter(b=>!b.acknowledgedAt).map(b=><div className="border rounded p-3 text-sm" key={b.id}><Badge>{b.severity}</Badge><p className="my-2">{b.text}</p><div className="flex gap-2 flex-wrap"><Button size="sm" onClick={()=>briefingAction.mutate(b.id)}>Accept</Button>{voice.data?.voice_enabled!==false&&<Button size="sm" variant="outline" onClick={()=>speak(b.text)}><Volume2 className="mr-1 h-3 w-3"/>Play locally</Button>}{b.deepLink&&<Button size="sm" variant="ghost" asChild><Link href={b.deepLink}>Open item</Link></Button>}</div></div>)}</CardContent></Card>
    <div className="grid md:grid-cols-2 gap-4"><CommitmentPanel items={commitments.data?.commitments??[]} onAction={(id,a,dueAt)=>commitmentAction.mutate({id,action:a,dueAt})}/><PromisePanel items={promises.data?.promises??[]} onAdd={()=>setPromiseOpen(true)} onAction={(id,a)=>promiseAction.mutate({id,action:a})}/></div>
     <HandoffPanel items={handoffs.data?.handoffs??[]} onAccept={(id)=>handoffAction.mutate(id)} loading={handoffs.isLoading} error={handoffs.isError}/>
    {promiseOpen&&<PromiseForm missions={missions} onClose={()=>setPromiseOpen(false)} onSaved={()=>{setPromiseOpen(false);queryClient.invalidateQueries({queryKey:["/api/kay/promises"]})}}/>}
    <Card><CardHeader><CardTitle className="flex gap-2 text-[#005476]"><Clock/>Your Next 60 Minutes <Badge>{query.data?.settings.max_next_60_minutes_items ?? 6} max</Badge></CardTitle></CardHeader><CardContent><div className="flex gap-2 items-center mb-3 text-sm flex-wrap">Kay availability: <select aria-label="Kay availability" className="border rounded px-2 py-1" value={availability.data?.availability || "AVAILABLE"} onChange={e=>updateAvailability.mutate(e.target.value)}><option>AVAILABLE</option><option>BUSY</option><option>DO_NOT_ASSIGN</option><option>LEAVE</option></select><Button size="sm" variant="outline" onClick={()=>query.refetch()}>Refresh</Button></div>{(query.data?.next60Minutes ?? []).length ? <div className="space-y-2">{query.data!.next60Minutes.map(m=><MissionCard key={m.id} mission={m} action={action}/>)}</div> : <p className="text-muted-foreground text-sm py-3">You are clear for the next hour.</p>}</CardContent></Card>
    {sections.map(([title,items])=><Card key={title}><CardHeader className="py-4"><CardTitle className="text-base text-[#005476]">{title} <Badge variant="secondary">{items.length}</Badge></CardTitle></CardHeader><CardContent>{items.length?<div className="space-y-2">{items.slice(0,20).map(m=><MissionCard key={m.id} mission={m} action={action}/>)}</div>:<p className="text-sm text-muted-foreground">Nothing needs attention here right now.</p>}</CardContent></Card>)}
  </div>;
}

function CommitmentPanel({items,onAction}:{items:Commitment[];onAction:(id:number,a:"accept"|"complete"|"extend",dueAt?:string)=>void}) { const [extendId,setExtendId]=useState<number|null>(null);const [due,setDue]=useState(""); return <Card><CardHeader><CardTitle className="text-base text-[#005476]">My commitments</CardTitle></CardHeader><CardContent className="space-y-2">{items.length?items.slice().sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)).map(c=>{const status=c.status.toUpperCase();const canComplete=["ACCEPTED","EXTENDED","OVERDUE"].includes(status);return <div className="border rounded p-2 text-sm" key={c.id}><b>{c.action}</b><div className="text-muted-foreground">Status: {status} · Due {localDate(c.dueAt)}</div><div className="flex gap-2 mt-2 flex-wrap">{status==="PENDING"&&<Button size="sm" onClick={()=>onAction(c.id,"accept")}>Accept</Button>}{canComplete&&<Button size="sm" onClick={()=>onAction(c.id,"complete")}><CheckCircle2 className="mr-1 h-3 w-3"/>Complete</Button>}{canComplete&&<Button size="sm" variant="outline" onClick={()=>setExtendId(c.id)}>Extend</Button>}</div>{extendId===c.id&&<div className="flex gap-2 mt-2"><label className="text-xs">New due time<input aria-label="New commitment due time" type="datetime-local" className="block border rounded p-1 mt-1" value={due} onChange={e=>setDue(e.target.value)}/></label><Button size="sm" disabled={!due} onClick={()=>{onAction(c.id,"extend",new Date(due).toISOString());setExtendId(null)}}>Save due time</Button></div>}</div>}):<p className="text-sm text-muted-foreground">No commitments yet. Create one from a mission.</p>}</CardContent></Card>; }
function PromisePanel({items,onAdd,onAction}:{items:PromiseItem[];onAdd:()=>void;onAction:(id:number,a:"complete"|"cancel")=>void}) { const groups=useMemo(()=>["Overdue","Due Soon","Completed Today","Upcoming"].map(name=>[name,items.filter(p=>dueBucket(p)===name)] as [string,PromiseItem[]]),[items]); return <Card><CardHeader><CardTitle className="flex justify-between items-center text-base text-[#005476]">Customer promises<Button size="sm" onClick={onAdd}><Plus className="mr-1 h-3 w-3"/>Quick promise</Button></CardTitle></CardHeader><CardContent className="space-y-3">{groups.map(([name,list])=><div key={name}><h3 className="text-xs uppercase tracking-wide text-muted-foreground">{name} · {list.length}</h3>{list.sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)).map(p=>{const actionable=["PENDING","DUE_SOON","OVERDUE"].includes(p.status.toUpperCase());return <div className="border rounded p-2 mt-1 text-sm" key={p.id}><b>{p.promiseText}</b><div className="text-muted-foreground">Status: {p.status} · {p.importance} · {localDate(p.dueAt)}</div>{actionable&&<div className="flex gap-2 mt-2"><Button size="sm" onClick={()=>onAction(p.id,"complete")}>Mark complete</Button><Button size="sm" variant="ghost" onClick={()=>onAction(p.id,"cancel")}>Cancel</Button></div>}</div>})}</div>)}</CardContent></Card>; }
function HandoffPanel({items,onAccept,loading,error}:{items:Handoff[];onAccept:(id:number)=>void;loading:boolean;error:boolean}) {
  return <Card className="border-[#d39b45]"><CardHeader><CardTitle className="flex items-center gap-2 text-base text-[#005476]"><ArrowRight className="h-4 w-4"/>Promise handoffs</CardTitle></CardHeader><CardContent className="space-y-2">{loading?<p className="text-sm text-muted-foreground">Loading handoffs…</p>:error?<p className="text-sm text-red-700"><ShieldAlert className="mr-1 inline h-4 w-4"/>Unable to load promise handoffs. Retry by refreshing the page.</p>:items.length===0?<p className="text-sm text-muted-foreground">No promise handoffs are waiting for you.</p>:items.map(item=><div className="rounded-lg border border-[#ead5ad] bg-[#fffaf0] p-3 text-sm" key={item.id}><p className="font-medium">Promise from the original owner</p><p className="mt-1">{item.promise_text ?? item.promiseText}</p><p className="mt-1 text-xs text-slate-600">Originally owned by employee #{item.original_owner_id}. You are responsible for this handoff; this does not mean you made the original promise.</p><p className="text-xs text-slate-600">Due {localDate(item.due_at ?? item.dueAt)} · {item.importance ?? "NORMAL"}</p>{item.accepted_at?<Badge className="mt-2">Accepted</Badge>:<Button size="sm" className="mt-2" onClick={()=>onAccept(item.id)}>Accept handoff</Button>}</div>)}</CardContent></Card>;
}
function PromiseForm({missions,onClose,onSaved}:{missions:Mission[];onClose:()=>void;onSaved:()=>void}) { const owned=missions.filter(m=>m.leadId);const [leadId,setLeadId]=useState("");const [text,setText]=useState("");const [type,setType]=useState("CALL");const [importance,setImportance]=useState("NORMAL");const [due,setDue]=useState("");const save=useMutation({mutationFn:()=>apiRequest("POST","/api/kay/promises",{leadId:Number(leadId),promiseText:text,dueAt:new Date(due).toISOString(),importance,idempotencyKey:`promise-${leadId}-${Date.now()}`}),onSuccess:onSaved});const applyType=(value:string)=>{setType(value);if(value!=="CUSTOM")setText({CALL:"Call the customer",EMAIL:"Send the customer an update",QUOTE:"Send the requested quote",VIEWING:"Confirm the viewing details"}[value]||"");};return <div className="fixed inset-0 z-50 bg-black/30 p-4 flex items-center justify-center" role="dialog" aria-modal="true"><Card className="w-full max-w-md"><CardHeader><CardTitle>New customer promise</CardTitle></CardHeader><CardContent className="space-y-3">{owned.length===0?<p className="text-sm text-muted-foreground">A customer promise must be attached to one of your current mission leads.</p>:<><label className="block text-sm">Lead<select required className="w-full border rounded p-2 mt-1" value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Select a mission lead</option>{owned.map(m=><option key={m.id} value={m.leadId!}>Lead #{m.leadId} · {m.objective}</option>)}</select></label><label className="block text-sm">Quick type<select className="w-full border rounded p-2 mt-1" value={type} onChange={e=>applyType(e.target.value)}><option>CALL</option><option>EMAIL</option><option>QUOTE</option><option>VIEWING</option><option>CUSTOM</option></select></label><label className="block text-sm">Promise<textarea autoFocus className="w-full border rounded p-2 mt-1" rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="What will you do for this customer?"/></label><label className="block text-sm">Importance<select className="w-full border rounded p-2 mt-1" value={importance} onChange={e=>setImportance(e.target.value)}><option value="NORMAL">Normal</option><option value="IMPORTANT">Important</option></select></label><label className="block text-sm">Due (your local time)<input required type="datetime-local" className="w-full border rounded p-2 mt-1" value={due} onChange={e=>setDue(e.target.value)}/></label></>}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button disabled={!leadId||!text.trim()||!due||save.isPending} onClick={()=>save.mutate()}>Create promise</Button></div></CardContent></Card></div>; }

function MissionCard({mission,action}:{mission:Mission;action:any}) { const [open,setOpen]=useState(false);const complete=()=>action.mutate({id:mission.id,action:"complete",payload:{resultCode:"CONTACTED_OTHER",note:window.prompt("What happened? Optional.")?.slice(0,500)||""}});const title=mission.missionType==="RESCUE_LEAD_ASSIGNED"?"RESCUE LEAD ASSIGNED":mission.missionType==="RESCUE_RISK"?"RESCUE REVIEW PENDING":mission.missionType.replaceAll("_"," ");return <div id={`kay-mission-${mission.id}`} className="border rounded-xl p-3 space-y-2"><div className="flex items-center justify-between gap-2"><b className="text-sm text-[#005476]">{title}</b><Badge className={colors[mission.priority]||""}>{mission.priority} · {mission.priorityScore}</Badge></div><p className="text-sm">{mission.reasonDetails?.explanation||mission.objective}</p><details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">WHY THIS IS PRIORITY</summary>{mission.reasonDetails?.factors?.map(f=><div key={f.label}>{f.label} +{f.points}</div>)}</details><p className="text-xs text-muted-foreground">{mission.suggestedAction}</p><div className="flex flex-wrap gap-2">{mission.leadId&&<Button size="sm" variant="outline" asChild><Link href={`/admin/crm/${mission.leadId}`}>Open lead <ExternalLink className="ml-1 h-3 w-3"/></Link></Button>}{mission.status==="NEW"&&<Button size="sm" onClick={()=>action.mutate({id:mission.id,action:"accept"})}>Accept</Button>}{mission.status==="ACCEPTED"&&<Button size="sm" onClick={()=>action.mutate({id:mission.id,action:"start"})}>Start</Button>}{["ACCEPTED","IN_PROGRESS"].includes(mission.status)&&<><Button size="sm" variant="outline" onClick={()=>setOpen(!open)}>Commit</Button><Button size="sm" variant="secondary" onClick={complete}><CheckCircle2 className="mr-1 h-3 w-3"/>Complete</Button></>}</div>{open&&<CommitmentForm mission={mission} onDone={()=>setOpen(false)}/>}</div>; }
function CommitmentForm({mission,onDone}:{mission:Mission;onDone:()=>void}) { const [choice,setChoice]=useState("15");const [custom,setCustom]=useState("");const [laterDue,setLaterDue]=useState("");const [actionText,setActionText]=useState(mission.suggestedAction);const dueAt=choice==="later"?(laterDue?new Date(laterDue).toISOString():null):new Date(Date.now()+(choice==="custom"?Number(custom||15):Number(choice))*60000).toISOString();const save=useMutation({mutationFn:()=>apiRequest("POST","/api/kay/commitments",{missionId:mission.id,leadId:mission.leadId,action:actionText.trim(),dueAt,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,idempotencyKey:`mission-${mission.id}-${Date.now()}`}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["/api/kay/commitments"]});onDone();}});return <div className="flex flex-wrap items-center gap-2 bg-slate-50 p-2 rounded"><input aria-label="Commitment action" className="border rounded px-2 py-1 text-sm flex-1 min-w-48" value={actionText} onChange={e=>setActionText(e.target.value)} /><span className="text-xs text-muted-foreground">Due ({Intl.DateTimeFormat().resolvedOptions().timeZone})</span>{["10","15","30","60","later","custom"].map(v=><Button key={v} size="sm" variant={choice===v?"default":"outline"} onClick={()=>setChoice(v)}>{v==="later"?"Later":v==="custom"?"Custom":`${v}m`}</Button>)}{choice==="custom"&&<input aria-label="Custom minutes" className="w-20 border rounded px-2 py-1 text-sm" type="number" min="1" value={custom} onChange={e=>setCustom(e.target.value)}/>} {choice==="later"&&<input aria-label="Choose later due date" type="datetime-local" className="border rounded px-2 py-1 text-sm" value={laterDue} onChange={e=>setLaterDue(e.target.value)}/>}<Button size="sm" onClick={()=>save.mutate()} disabled={save.isPending||choice==="custom"&&!custom||choice==="later"&&!laterDue||!actionText.trim()}>Save</Button></div>; }